### ISSUE TITLE
br.links() returning <generator object __call__ at 0x12f1500>

### ISSUE THREAD

**Issue by ffaggiani** [faizann24/XssPy#3]
Hi, my problem is that the function br.links() is returning : "generator object __call__ at 0x12f1500"
but  if print br.response().read() i can see html code well formed with links inside.

I have tried to build a list from br.links() but its not working...

Any help?

Thanks.

Fab

**Comment by faizann24** [comment]
Try doing something like this. Br.links() is returning a tuple if used in a loop.

for i in br.links():
     print i

You'll have tuples instead of a list. You can parse it and make it a list from it.

![fsecurify](https://cloud.githubusercontent.com/assets/17704628/16048990/85066ff8-326f-11e6-8221-b78888471553.png)

**Comment by ffaggiani** [comment]
OK, done. Now i can see the links.

Thanks!
